local _G = GLOBAL
--保鲜设置
_G.TUNING.PERISH_FRIDGE_MULT = 0
_G.TUNING.PERISH_SALTBOX_MULT = -0.5
_G.TUNING.PERISH_MUSHROOM_LIGHT_MULT = 0


_G.TUNING.STACK_SIZE_LARGEITEM = 40
_G.TUNING.STACK_SIZE_MEDITEM = 40
_G.TUNING.STACK_SIZE_SMALLITEM = 40

--骨灰盒
AddPrefabPostInit("sisturn", function(inst)
	inst:AddTag("fridge")
end)